### PR TITLE
Refresh the table on enter key

### PR DESCRIPTION
**Pull request by Ashesh3**
Instead of exiting the program and having the user to run it again every time, It's better to keep the window open and just wait for an enter key to update the table, this seems more convenient.
Note: the `presence` function is renamed to `get_presence` so that it does not collide with the local variable's name (Python complains about this)

### CODE REVIEW

**Comment by OwOHamper** [comment]
I'll rename the variable but on the key is bad idea because it adds keyboard input delay.

**Comment by Ashesh3** [comment]
> I'll rename the variable but on the key is bad idea because it adds keyboard input delay.

Sorry, i didn't really get what you mean by keyword input delay here. The table is initially displayed once and then it just stays there until the user presses enter key, then it just refreshes itself.

**Comment by OwOHamper** [comment]
hmmmm I thought you would like press keybind in-game and it would refresh. Alright I'll commit in few hours

**Comment by Ashesh3** [comment]
> hmmmm I thought you would like press keybind in-game and it would refresh. Alright I'll commit in few hours

Thanks! sounds good. 

Also in-game keybind sounds like a good separate future, but I doubt it would help much though because most users would need to alt-tab out of the game to access this table anyways, so just hitting enter key inside the console window of this app sounds like a simpler and more user friendly option.

**Comment by OwOHamper** [comment]
ye but thing about in-game keybinds is that they add a lot of input delay

**Comment by OwOHamper** [comment]
Alright added the feature tutorial video coming soon

**Pull request closed without merging**
